services:
  postgres_criminal_db:
    container_name: postgres_criminal_db
    image: postgres:16
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
      - POSTGRES_DB=criminal_minds
    networks:
      - criminalnet
    env_file:
      - ./docker-secrets
    volumes:
      - db_postgres_criminal_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin_criminal_db:
    container_name: pgadmin_criminal_db
    image: dpage/pgadmin4:latest
    networks:
      - criminalnet
    env_file:
      - ./docker-secrets-pgadmin
    volumes:
      - pgadmin_criminal:/var/lib/pgadim
    ports:
      - "9080:80"
    links:
      - postgres_criminal_db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - criminalnet
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Asegura que Kafka se anuncie correctamente dentro de la red Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - criminalnet
    volumes:
      - kafka-data:/var/lib/kafka/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es-container
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  db_postgres_criminal_data:
  pgadmin_criminal:
  zookeeper-data:
  zookeeper-log:
  kafka-data:


networks:
  criminalnet:
    driver: bridge

